INSERT INTO public."Camp_Data" ("CampAdminId", "Name", "Description", "LocationAddress", "CreatedBy", "CreatedOn", "UpdatedBy", "UpdatedOn", "IsDeleted", "District")
VALUES
    (1, 'Thiruvananthapuram Relief Camp', 'Providing shelter and food for flood victims', 'Location Address 1', NULL, NOW(), NULL, NULL, false, 'Thiruvananthapuram'),
    (4, 'Kollam Support Center', 'Offering medical aid and basic necessities', 'Location Address 2', NULL, NOW(), NULL, NULL, false, 'Kollam'),
    (6, 'Pathanamthitta Refugee Camp', 'Temporary housing and food supplies', 'Location Address 3', NULL, NOW(), NULL, NULL, false, 'Pathanamthitta'),
    (1, 'Alappuzha Flood Relief', 'Assisting with flood recovery and rehabilitation', 'Location Address 4', NULL, NOW(), NULL, NULL, false, 'Alappuzha'),
    (4, 'Kottayam Emergency Shelter', 'Emergency shelter and food distribution', 'Location Address 5', NULL, NOW(), NULL, NULL, false, 'Kottayam'),
    (6, 'Idukki Disaster Relief', 'Providing aid and support for disaster victims', 'Location Address 6', NULL, NOW(), NULL, NULL, false, 'Idukki'),
    (1, 'Ernakulam Aid Center', 'Offering medical aid and food supplies', 'Location Address 7', NULL, NOW(), NULL, NULL, false, 'Ernakulam'),
    (4, 'Thrissur Relief Camp', 'Temporary housing and basic necessities', 'Location Address 8', NULL, NOW(), NULL, NULL, false, 'Thrissur'),
    (6, 'Palakkad Support Camp', 'Providing shelter and food for displaced families', 'Location Address 9', NULL, NOW(), NULL, NULL, false, 'Palakkad'),
    (1, 'Malappuram Emergency Relief', 'Assisting with emergency relief and recovery', 'Location Address 10', NULL, NOW(), NULL, NULL, false, 'Malappuram'),
    (4, 'Kozhikode Refugee Center', 'Temporary housing and medical aid', 'Location Address 11', NULL, NOW(), NULL, NULL, false, 'Kozhikode'),
    (6, 'Wayanad Disaster Support', 'Providing aid and support for disaster victims', 'Location Address 12', NULL, NOW(), NULL, NULL, false, 'Wayanad'),
    (1, 'Kannur Relief Camp', 'Offering shelter and food for flood victims', 'Location Address 13', NULL, NOW(), NULL, NULL, false, 'Kannur'),
    (4, 'Kasaragod Support Center', 'Assisting with flood recovery and rehabilitation', 'Location Address 14', NULL, NOW(), NULL, NULL, false, 'Kasaragod'),
    (6, 'Thiruvananthapuram Aid Camp', 'Providing medical aid and basic necessities', 'Location Address 15', NULL, NOW(), NULL, NULL, false, 'Thiruvananthapuram'),
    (1, 'Kollam Relief Shelter', 'Temporary housing and food distribution', 'Location Address 16', NULL, NOW(), NULL, NULL, false, 'Kollam'),
    (4, 'Pathanamthitta Emergency Camp', 'Offering shelter and food for displaced families', 'Location Address 17', NULL, NOW(), NULL, NULL, false, 'Pathanamthitta'),
    (6, 'Alappuzha Support Camp', 'Providing aid and support for disaster victims', 'Location Address 18', NULL, NOW(), NULL, NULL, false, 'Alappuzha'),
    (1, 'Kottayam Disaster Relief', 'Assisting with emergency relief and recovery', 'Location Address 19', NULL, NOW(), NULL, NULL, false, 'Kottayam'),
    (4, 'Idukki Refugee Camp', 'Temporary housing and medical aid', 'Location Address 20', NULL, NOW(), NULL, NULL, false, 'Idukki'),
    (6, 'Ernakulam Emergency Support', 'Providing shelter and food for flood victims', 'Location Address 21', NULL, NOW(), NULL, NULL, false, 'Ernakulam'),
    (1, 'Thrissur Aid Center', 'Offering medical aid and basic necessities', 'Location Address 22', NULL, NOW(), NULL, NULL, false, 'Thrissur'),
    (4, 'Palakkad Relief Camp', 'Temporary housing and food distribution', 'Location Address 23', NULL, NOW(), NULL, NULL, false, 'Palakkad'),
    (6, 'Malappuram Support Shelter', 'Providing shelter and food for displaced families', 'Location Address 24', NULL, NOW(), NULL, NULL, false, 'Malappuram'),
    (1, 'Kozhikode Disaster Relief', 'Assisting with emergency relief and recovery', 'Location Address 25', NULL, NOW(), NULL, NULL, false, 'Kozhikode'),
    (4, 'Wayanad Refugee Center', 'Temporary housing and medical aid', 'Location Address 26', NULL, NOW(), NULL, NULL, false, 'Wayanad'),
    (6, 'Kannur Emergency Support', 'Providing aid and support for disaster victims', 'Location Address 27', NULL, NOW(), NULL, NULL, false, 'Kannur'),
    (1, 'Kasaragod Relief Shelter', 'Offering shelter and food for flood victims', 'Location Address 28', NULL, NOW(), NULL, NULL, false, 'Kasaragod'),
    (4, 'Thiruvananthapuram Support Camp', 'Assisting with flood recovery and rehabilitation', 'Location Address 29', NULL, NOW(), NULL, NULL, false, 'Thiruvananthapuram'),
    (6, 'Kollam Aid Center', 'Providing medical aid and basic necessities', 'Location Address 30', NULL, NOW(), NULL, NULL, false, 'Kollam'),
    (1, 'Pathanamthitta Relief Camp', 'Temporary housing and food distribution', 'Location Address 31', NULL, NOW(), NULL, NULL, false, 'Pathanamthitta'),
    (4, 'Alappuzha Emergency Shelter', 'Offering shelter and food for displaced families', 'Location Address 32', NULL, NOW(), NULL, NULL, false, 'Alappuzha'),
    (6, 'Kottayam Support Camp', 'Providing aid and support for disaster victims', 'Location Address 33', NULL, NOW(), NULL, NULL, false, 'Kottayam'),
    (1, 'Idukki Disaster Relief', 'Assisting with emergency relief and recovery', 'Location Address 34', NULL, NOW(), NULL, NULL, false, 'Idukki'),
    (4, 'Ernakulam Refugee Camp', 'Temporary housing and medical aid', 'Location Address 35', NULL, NOW(), NULL, NULL, false, 'Ernakulam'),
    (6, 'Thrissur Emergency Support', 'Providing shelter and food for flood victims', 'Location Address 36', NULL, NOW(), NULL, NULL, false, 'Thrissur'),
    (1, 'Palakkad Aid Center', 'Offering medical aid and basic necessities', 'Location Address 37', NULL, NOW(), NULL, NULL, false, 'Palakkad'),
    (4, 'Malappuram Relief Camp', 'Temporary housing and food distribution', 'Location Address 38', NULL, NOW(), NULL, NULL, false, 'Malappuram'),
    (6, 'Kozhikode Support Shelter', 'Providing shelter and food for displaced families', 'Location Address 39', NULL, NOW(), NULL, NULL, false, 'Kozhikode'),
    (1, 'Wayanad Disaster Relief', 'Assisting with emergency relief and recovery', 'Location Address 40', NULL, NOW(), NULL, NULL, false, 'Wayanad'),
    (4, 'Kannur Refugee Center', 'Temporary housing and medical aid', 'Location Address 41', NULL, NOW(), NULL, NULL, false, 'Kannur'),
    (6, 'Kasaragod Emergency Support', 'Providing aid and support for disaster victims', 'Location Address 42', NULL, NOW(), NULL, NULL, false, 'Kasaragod');