INSERT INTO public."Items" ("Name", "Description", "CreatedBy", "CreatedOn", "UpdatedBy", "UpdatedOn", "IsDeleted", "PostedDate")
VALUES
    ('Bed', 'Single beds for sleeping', NULL, NOW(), NULL, NULL, false, NOW()),
    ('Torch', 'Battery-operated torches for lighting', NULL, NOW(), NULL, NULL, false, NOW()),
    ('Chair', 'Plastic chairs for seating', NULL, NOW(), NULL, NULL, false, NOW()),
    ('Blanket', 'Warm blankets for cold weather', NULL, NOW(), NULL, NULL, false, NOW()),
    ('First Aid Kit', 'Basic first aid supplies', NULL, NOW(), NULL, NULL, false, NOW()),
    ('Water Bottle', 'Reusable water bottles', NULL, NOW(), NULL, NULL, false, NOW()),
    ('Tent', 'Temporary tents for shelter', NULL, NOW(), NULL, NULL, false, NOW()),
    ('Food Pack', 'Non-perishable food items', NULL, NOW(), NULL, NULL, false, NOW()),
    ('Clothing', 'Basic clothing items', NULL, NOW(), NULL, NULL, false, NOW()),
    ('Sleeping Bag', 'Sleeping bags for warmth', NULL, NOW(), NULL, NULL, false, NOW()),
    ('Flashlight', 'Handheld flashlights', NULL, NOW(), NULL, NULL, false, NOW()),
    ('Cooking Stove', 'Portable cooking stoves', NULL, NOW(), NULL, NULL, false, NOW()),
    ('Mosquito Net', 'Nets to protect against mosquitoes', NULL, NOW(), NULL, NULL, false, NOW()),
    ('Sanitary Kit', 'Sanitary supplies for hygiene', NULL, NOW(), NULL, NULL, false, NOW()),
    ('Pillow', 'Comfortable pillows for sleeping', NULL, NOW(), NULL, NULL, false, NOW()),
    ('Towel', 'Bath towels', NULL, NOW(), NULL, NULL, false, NOW()),
    ('Soap', 'Bars of soap for cleaning', NULL, NOW(), NULL, NULL, false, NOW()),
    ('Toothbrush', 'Toothbrushes for dental hygiene', NULL, NOW(), NULL, NULL, false, NOW()),
    ('Toothpaste', 'Tubes of toothpaste', NULL, NOW(), NULL, NULL, false, NOW()),
    ('Shampoo', 'Bottles of shampoo', NULL, NOW(), NULL, NULL, false, NOW()),
    ('Diapers', 'Disposable diapers for infants', NULL, NOW(), NULL, NULL, false, NOW()),
    ('Baby Food', 'Baby food jars and packets', NULL, NOW(), NULL, NULL, false, NOW()),
    ('Hand Sanitizer', 'Bottles of hand sanitizer', NULL, NOW(), NULL, NULL, false, NOW()),
    ('Face Mask', 'Disposable face masks', NULL, NOW(), NULL, NULL, false, NOW()),
    ('Gloves', 'Disposable gloves', NULL, NOW(), NULL, NULL, false, NOW()),
    ('Raincoat', 'Waterproof raincoats', NULL, NOW(), NULL, NULL, false, NOW()),
    ('Umbrella', 'Portable umbrellas', NULL, NOW(), NULL, NULL, false, NOW()),
    ('Laundry Detergent', 'Packets of laundry detergent', NULL, NOW(), NULL, NULL, false, NOW()),
    ('Dish Soap', 'Bottles of dish soap', NULL, NOW(), NULL, NULL, false, NOW()),
    ('Cleaning Supplies', 'General cleaning supplies', NULL, NOW(), NULL, NULL, false, NOW()),
    ('Broom', 'Brooms for cleaning', NULL, NOW(), NULL, NULL, false, NOW()),
    ('Mop', 'Mops for cleaning', NULL, NOW(), NULL, NULL, false, NOW()),
    ('Bucket', 'Plastic buckets', NULL, NOW(), NULL, NULL, false, NOW()),
    ('Dustpan', 'Dustpans for cleaning', NULL, NOW(), NULL, NULL, false, NOW()),
    ('Trash Bags', 'Rolls of trash bags', NULL, NOW(), NULL, NULL, false, NOW()),
    ('Toilet Paper', 'Rolls of toilet paper', NULL, NOW(), NULL, NULL, false, NOW()),
    ('Paper Towels', 'Rolls of paper towels', NULL, NOW(), NULL, NULL, false, NOW()),
    ('Hand Soap', 'Bottles of hand soap', NULL, NOW(), NULL, NULL, false, NOW()),
    ('Disinfectant Wipes', 'Packets of disinfectant wipes', NULL, NOW(), NULL, NULL, false, NOW()),
    ('Laundry Basket', 'Plastic laundry baskets', NULL, NOW(), NULL, NULL, false, NOW()),
    ('Clothesline', 'Clotheslines for drying clothes', NULL, NOW(), NULL, NULL, false, NOW()),
    ('Clothespins', 'Packets of clothespins', NULL, NOW(), NULL, NULL, false, NOW());